version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tarefas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2016010124
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped  # Adicione esta linha para o PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy  # Espera até o banco estar pronto
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tarefas
      DB_USER: postgres
      DB_PASS: 2016010124
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data: